name: SCDenizenBridge
version: '${version}'
main: minat0.scdenizenbridge.SCDenizenBridge
api-version: 1.19
depend: [ SimpleClans, Depenizen ]
authors: [ Minat0 ]
description: A simple bridge between Denizen and SimpleClans. 
